# Generated by Django 4.2.4 on 2023-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                ("born_date", models.CharField(max_length=150)),
                ("born_location", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=150)),
            ],
        ),
    ]
