# Generated by Django 4.2.4 on 2023-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("fullname", "born_date", "born_location", "description"),
                name="authors",
            ),
        ),
    ]
