# Generated by Django 4.2.4 on 2023-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0003_alter_author_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.CharField(),
        ),
    ]
