# Generated by Django 4.2.4 on 2023-08-27 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tagname",
            new_name="tag",
        ),
    ]
