# Generated by Django 4.2.4 on 2023-08-27 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_rename_tagname_tag_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag",
            new_name="tagname",
        ),
    ]
