# Generated by Django 4.2.4 on 2023-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_rename_tag_tag_tagname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tagname",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
